name: CI/CD Pipeline for Model Training, Testing, and Docker Deployment

on:
  push:
    branches:
      - main  # Runs on every push to main branch

jobs:
  
  # 🔥 Step 1: Train, Build & Test the Application
  train_build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all files and folders are pulled

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install build

      - name: Run Training, Build, and Test
        working-directory: build_bikesharing/Application  # Ensure correct path
        run: python -m build

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-application
          path: build_bikesharing/Application/dist/  # Adjust if output path differs

  # 🔥 Step 2: Build and Push Docker Image
  build_docker:
    runs-on: ubuntu-latest
    needs: train_build_test  # Runs only if Step 1 is successful
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all files and folders are present

      - name: Debug - List Files to Verify Dockerfile Location
        run: |
          echo "Listing contents of build_bikesharing/bike_sharing_api/"
          ls -l build_bikesharing/bike_sharing_api/

      - name: Download Built Application
        uses: actions/download-artifact@v4
        with:
          name: built-application
          path: build_bikesharing/Application/dist/

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        working-directory: build_bikesharing/bike_sharing_api  # Ensure correct path
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bike_sharing_api:latest .

      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bike_sharing_api:latest
